name: build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      name:
        description: 'description'
        required: false
        default: ''

permissions:
  contents: read

jobs:

  build:

    name: ${{ matrix.platform }}, py${{ matrix.python-version }}, ${{ matrix.install-level }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [
          ubuntu-latest,
          windows-latest,
          macos-latest,
        ]
        python-version: [
          "3.11",
          "3.12",
          "3.13",
        ]
        install-level: [
          system,
          user,
        ]

    steps:

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Check specs of the machine -- Linux
      if: startsWith(matrix.platform, 'ubuntu')
      run: |
        echo "CPU info (lscpu):"
        lscpu
        echo "Memory info (free -h):"
        free -h
        echo "Disk info (df -h):"
        df -h
        echo "OS info (uname -a):"
        uname -a
    - name: Check specs of the machine -- Windows
      if: startsWith(matrix.platform, 'windows')
      run: |
        echo "System info (systeminfo):"
        systeminfo
    - name: Check specs of the machine -- MacOS
      if: startsWith(matrix.platform, 'macos')
      run: |
        echo "CPU info (sysctl -n machdep.cpu.brand_string):"
        sysctl -n machdep.cpu.brand_string
        echo "Memory info (sysctl -n hw.memsize):"
        sysctl -n hw.memsize
        echo "Disk info (df -h):"
        df -h
        echo "OS info (uname -a):"
        uname -a

    - name: Install package with pip dependencies -- system-level
      if: matrix.install-level == 'system'
      run: |
        pip install -v -e .
    - name: Install package with pip dependencies -- user-level
      if: matrix.install-level == 'user'
      run: |
        pip install -v -e . --user

    - name: Check installed packages
      run: |
        pip list

    - name: Run pytest and generate coverage report
      run: |
        pip install pytest pytest-cov
        python -m pytest --capture=tee-sys --cov=torch_linear_regression --cov-report=xml:coverage.xml --color=yes

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
        fail_ci_if_error: false
        verbose: true
